src/objects/Custom_Event__c.object
<CustomObject>
    <fields>
        <fullName>Attached_to__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attached to</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Custom Events</relationshipLabel>
        <relationshipName>Custom_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Custom Events (Contact)</relationshipLabel>
        <relationshipName>Events1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting for approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <label>Custom Event</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Custom Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Free_time__c.object
<CustomObject>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Free time</label>
    <nameField>
        <displayFormat>FT-{0000}</displayFormat>
        <label>Free time Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Free times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateEventController.cls
public without sharing class CreateEventController {
    public Custom_Event__c event { get; set; }
    public Contact objContact { get; set; }

    public CreateEventController() {
        event = new Custom_Event__c();
        objContact = new Contact();
    }

    public Contact createOrGetContact() {
        User guestUser = [SELECT Id FROM User Where Username = :Constants.GUEST_USER_NAME];
        List<Contact> contacts = [SELECT Id,FirstName,LastName FROM Contact WHERE Email = :objContact.Email AND LastName = :objContact.LastName];
        if (contacts.isEmpty()) {
            Contact newContact = new Contact(
                    FirstName = objContact.FirstName,
                    LastName = objContact.LastName,
                    Email = objContact.Email,
                    OwnerId = guestUser.Id
            );

            insert newContact;
            return newContact;
        } else {
            return contacts.get(0);
        }
    }

    public PageReference save() {
        createOrGetContact();
        Boolean checkOnFreeTime = false;

        List<Free_Time__c>freeTimes = [
                SELECT Start_Time__c, End_Time__c
                From Free_Time__c
                WHERE Start_Time__c <= :event.Start_Time__c
                AND End_Time__c >= :event.Start_Time__c
                AND End_Time__c >= :event.End_Time__c
        ];

        if (!freeTimes.isEmpty()) {
            checkOnFreeTime = true;
        }

        if (checkOnFreeTime == true) {
            try {
                Custom_Event__c objEvent = new Custom_Event__c(
                        Start_Time__c = event.Start_Time__c,
                        End_Time__c = event.End_Time__c,
                        Subject__c = event.Subject__c,
                        Status__c = Constants.WAITING_FOR_APPROVAL_STATUS,
                        Contact__c = createOrGetContact().Id,
                        Attached_to__c = Constants.CONTACT_MANAGER_ID
                );
                insert objEvent;

                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Success! Event sent for review.');
                ApexPages.addMessage(msg);

                event = new Custom_Event__c(
                        Start_Time__c = null,
                        End_Time__c = null,
                        Subject__c = null
                );
                objContact = new Contact(
                        FirstName = null,
                        LastName = null,
                        Email = null
                );
                return null;


            } catch (Exception ex) {
                ApexPages.addMessages(ex);
                return null;
            }
        } else {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'No meetings are held at this time.');
            ApexPages.addMessage(msg);
            return null;
        }
    }
}