src/objects/Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Finished__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Finished</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Finished_by__c</fullName>
        <label>Finished by</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <label>Start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Upcoming</fullName>
                    <default>true</default>
                    <label>Upcoming</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MilestoneTriggerHandler.cls
public with sharing class MilestoneTriggerHandler extends TriggerHandler{
    public override void beforeUpdate() {
        checkAndUpdateStatus((List<Milestone__c>) Trigger.new);
    }

    private void checkAndUpdateStatus(List<Milestone__c> milestones){
        for(Milestone__c ms: milestones){
            if(ms.Finished__c == true){
                ms.Status__c = Constants.MILESTONE_STATUS_CLOSED;
                ms.Finished_by__c = System.today();
            }
            if(ms.Start_date__c != null && ms.Finished__c == false){
                ms.Status__c = Constants.MILESTONE_STATUS_INPROGRESS;
            }
        }
    }
}