src/objects/Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Finished__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Finished</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Finished_by__c</fullName>
        <label>Finished by</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Upcoming</fullName>
                    <default>true</default>
                    <label>Upcoming</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Finished_by__c</fullName>
        <label>Fnished by</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_is_finished__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project is finished</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectTriggerHandler.cls
public with sharing class ProjectTriggerHandler extends TriggerHandler {

    public override void beforeUpdate() {
        checkAndUpdateDateFnished((List<Project__c>) Trigger.new);
        //checkClosedMilestones((List<Project__c>) Trigger.new);
    }

    private void checkAndUpdateDateFnished(List<Project__c> projects) {
        for (Project__c project : projects) {
            Project__c oldProject = (Project__c) System.Trigger.oldMap.get(project.Id);
            if (oldProject.Project_is_finished__c == false && project.Project_is_finished__c == true) {
                project.Status__c = Constants.STATUS_CLOSED;
                checkClosedMilestones(project);
                return;
            }

            if (oldProject.Project_is_finished__c == true && project.Project_is_finished__c == false
                    && project.Status__c == Constants.STATUS_CLOSED) {
                project.Status__c = Constants.STATUS_INPROGRESS;
                project.Finished_by__c = null;
                return;
            }

            if (oldProject.Status__c != Constants.STATUS_CLOSED && project.Status__c == Constants.STATUS_CLOSED) {
                project.Project_is_finished__c = true;
                checkClosedMilestones(project);
                return;
            }

            if (project.Finished_by__c != null || (oldProject.Finished_by__c != project.Finished_by__c)) {
                project.Project_is_finished__c = true;
                project.Status__c = Constants.STATUS_CLOSED;
            }
        }


//        List<Milestone__c> milestone = [SELECT Id, Finished__c, Finished_by__c From Milestone__c WHERE Project__c IN: projects];
//        Date milestoneDateFinished;
//        Date maxMilestoneDateFinished;
//        for(Milestone__c ms: milestone){
//            milestoneDateFinished = ms.Finished_by__c;
//            if(milestoneDateFinished > ms.Finished_by__c){
//                maxMilestoneDateFinished = milestoneDateFinished;
//            }
//            else{
//                maxMilestoneDateFinished = ms.Finished_by__c;
//            }
//        }
//        for (Project__c project: projects){
//            System.debug('milestone-->' + milestone);
//            if(project.Project_is_finished__c == true && System.today() >= maxMilestoneDateFinished){
//                project.Finished_by__c = System.today();
//            }
//            else if(System.today() < maxMilestoneDateFinished){
//            project.addError('Not all milestones is finished');
//            }
//        }

    }
    private void checkClosedMilestones(Project__c project) {
        if (project.Status__c == Constants.STATUS_CLOSED) {
            List<Milestone__c> milestones = [SELECT Id, Status__c FROM Milestone__c WHERE Project__c = :project.Id];
            for (Milestone__c milestone : milestones) {
                if (milestone.Status__c != Constants.STATUS_CLOSED) {
                    project.addError('Unable to close the project because there are unclosed milestones');
                }
            }
        }

    }
}